#---------------------------
# Toplevel makefile for gapy
#---------------------------

all:
	cd src  ; make
	cd EXPRO  ; make
#	cd f2py ; make
	cd test ; make

clean:
	cd src ; make clean
	cd EXPRO ; make clean
	cd f2py ; make clean
	cd test ; make clean

.IGNORE:
