#---------------------------
# Toplevel makefile for gapy
#---------------------------

all:
	cd geo  ; make
	cd expro ; make
#	cd f2py ; make
	cd test ; make

clean:
	cd geo ; make clean
	cd expro ; make clean
	cd f2py ; make clean
	cd test ; make clean

.IGNORE:
