export EXTRA_LIBS = \
       ${GACODE_ROOT}/neo/src/neo_lib.a \
       ${GACODE_ROOT}/shared/nclass/nclass_lib.a \
       ${GACODE_ROOT}/tglf/src/tglf_lib.a \
       ${GACODE_ROOT}/cgyro/src/cgyro_lib.a \
       ${GACODE_ROOT}/f2py/expro/expro_lib.a \
       ${GACODE_ROOT}/f2py/geo/geo_lib.a \
       ${GACODE_ROOT}/shared/math/math_lib.a \
       ${GACODE_ROOT}/shared/UMFPACK/UMFPACK_lib.a \
       ${GACODE_ROOT}/shared/landau/landau.o \
       ${GACODE_ROOT}/shared/landau/gyrotransformation.o
