#---------------------------
# Toplevel makefile for gapy
#---------------------------

all:
	cd test_geo  ; make
	cd test_expro  ; make
	cd test_expro_plot  ; make

clean:
	cd test_geo ; make clean
	cd test_expro ; make clean
	cd test_expro_plot ; make clean

.IGNORE:
