  MODULE mhdcom 
  USE mhdpar,ONLY  :  nw,nh,nwh,nfcoil,nsilop,nesum,magpr2,          &
                      nvessel,nrogow
     IMPLICIT NONE
!
      REAL *8                                                        &
                      psifctr,pol_flux_lim, psibdry, psiaxis,        &
                      rma, zma, xsep, ysep,                          &
                      bigblk, psi1d(nwh), psi(nw,nh), pcurrent(nwh), &
                      psitemp(nfcoil), block1, plasma, psslim, hotw, &
                      hoth, hotrad, rsmall, rsilim, zsilim, arbox,   &
                      curmax(nfcoil)
!
!
      INTEGER         ix, isym, mfcinv, ivertsbl
      CHARACTER*8     greentab, mhdmode, mhdmethd
!
! --- the following are Green's table arrays generated by
! --- EFUND (the Green's table generator for EFIT).
! --- note that some of these arrays are used as storage for other
! --- things when the fixed boundary model is selected - in which case
! --- the Green's functions are not needed.
!
! --- ecoil current coupling
!
      REAL *8                                                          &
                        rsilec(nsilop,nesum), rmp2ec(magpr2,nesum),    &
                        rfcec(nfcoil,nesum), recec(nesum,nesum),       &
                        rsisec(nesum), gridec(nwh,nesum)
!
! --- vessel coupling
!
      REAL *8                                                           &
                        rsilvs(nsilop,nvessel), rmp2vs(magpr2,nvessel), &
                        rfcvs(nfcoil,nvessel), rvsfc(nvessel,nfcoil), &
                        rvsec(nvessel,nesum), rvsvs(nvessel,nvessel), &
                        gridvs(nwh,nvessel)
!
! --- grid, vessel and grid, plasma
!
      REAL *8                                                          &
                    gridfc(nwh,nfcoil), gridpc(nwh,nw)
!
! --- fcoil to psilop, magnetic probe, and Rogowski coupling
!
      REAL *8                                                          &
                        rsilfc(nsilop,nfcoil), rmp2fc(magpr2,nfcoil),  &
                        rgowfc(nrogow,nfcoil)
!
! --- fcoil to fcoil and plasma to fcoil
!
      REAL *8                                                          &
                           rfcfc(nfcoil,nfcoil), rfcpc(nfcoil,nwh)
!
! --- plasma to psiloop, probes and Rogowski
!
      REAL *8                                                          & 
                       rsilpc(nsilop,nwh), rmp2pc(magpr2,nwh),         &
                       rgowpc(nrogow,nwh)
      REAL *8                                                          &
                      zero(nwh), wzero(nwh)
!
   END MODULE mhdcom
