!
  MODULE TRANSP
        USE nrtype,        ONLY : DP,I4B,SP
        USE beam_structure,ONLY : neutral_beam
        USE fast_ion_diffusion ,ONLY :  fidif
        IMPLICIT NONE
        SAVE
        PRIVATE
        INTEGER,PARAMETER :: strlngth = 128
        INTEGER,PARAMETER :: kprim = 3
        INTEGER,PARAMETER,PUBLIC :: mfi  = 2      ! # fast beam species
        INTEGER,PARAMETER,PUBLIC :: ndifbep   = 20  ! size of fdifbe and edifbe
        INTEGER,PARAMETER,PUBLIC  :: nfusbb =8 
!
        !fus_tablebb_12(nfusbb) depends on reactions defined, 
        !see sub get_nboutput.f90
        LOGICAL,PUBLIC :: nbi_init,use_nubeam
        LOGICAL,PUBLIC :: use_ufile
        INTEGER,PUBLIC :: nubeam_version
        LOGICAL, PUBLIC :: nlbout
        LOGICAL,PUBLIC :: nubeam_init
        CHARACTER(len = strlngth) ,PUBLIC :: runid ='not_set'
        CHARACTER(len = strlngth) ,PUBLIC :: z_georoot=' ' 
        CHARACTER(len = strlngth) ,PUBLIC :: z_fpproot=' '
        CHARACTER(len = strlngth) ,PUBLIC :: z_fppxtra=' '
        CHARACTER(len = strlngth) ,PUBLIC :: xp_eqdsk_name
        CHARACTER(len = 48)  ,PUBLIC :: fus_tablebb_12(nfusbb)
        CHARACTER(len = 256) ,PUBLIC :: beam_data_ufile
        CHARACTER(len = 256) ,PUBLIC :: beam_data_namelist
        CHARACTER(len = 256) ,PUBLIC :: nubeam_state_path
        CHARACTER(len = 256) ,PUBLIC :: nubeam_profile_path
        CHARACTER(len = 256) ,PUBLIC :: profile_save_file
        CHARACTER(len = 256) ,PUBLIC :: xplasma_save_file
        CHARACTER(len = 256) ,PUBLIC :: nubeam_namelist_cpy
        CHARACTER(len = 256) ,PUBLIC :: state_save_file
        CHARACTER(len = 256) ,PUBLIC :: xplasma_file
        CHARACTER(len = 256) ,PUBLIC :: state_file
        CHARACTER(len = 256) ,PUBLIC :: profile_file
        CHARACTER(len = 256) ,PUBLIC :: nubeam_xplasma_path
        CHARACTER(len = 8 )  ,PUBLIC :: xp_namep(kprim) !length = namep length
        CHARACTER(len = 8 )  ,PUBLIC :: xp_namen(kprim) !length = namep length
        CHARACTER(len = 8 )  ,PUBLIC :: nameb_nubeam(mfi)
        CHARACTER(len=24)    ,PUBLIC :: nubeam_root
!
        !following need to be defined from input inone
        !first used in set_nbdims
        LOGICAL,PUBLIC :: nlfhe3,nlfhe4, nlfst,nlfsp, nlusf3
        LOGICAL,PUBLIC :: nlusfa,nlusft,nlusfp,nlfatom,nlbfpp
        LOGICAL,PUBLIC :: nlminsv,nlbbcx,nlebei,nlbcpa
        LOGICAL,PUBLIC :: nlbcde, nlbcoh,nlorbo,nlntmj
        LOGICAL,PUBLIC :: nlbflr,nlbgflr,nlfbon, nlcprb,nlfbmflr
        LOGICAL,PUBLIC :: nlfdep,nlsym2b,nlsawb,nlsawf,orbit_losses
        LOGICAL,PUBLIC,   DIMENSION(:),ALLOCATABLE  :: nlfbmfpp
!
!
!
!
        INTEGER,PARAMETER,PUBLIC  :: inzri = 10 !no of radial grid zones.
                                        !NOTE input nzones must be a multiple
                                        !of inzri, only inzri=10,20 are allowed
        INTEGER,PUBLIC :: nxskpb
        INTEGER,PUBLIC :: nsbeam,ng, nprim_tr,xp_nneu
        INTEGER,PUBLIC :: nmini,nerngfi,ncoils,nchdvp
        INTEGER,PUBLIC :: id_vol,id_cxarea,id_RBt
        INTEGER,PUBLIC :: nmcurb,nbbox,indx_neut,nneu_12
        INTEGER,PUBLIC :: nubeam_restart,save_nubeam_input
        INTEGER,PUBLIC :: nubeam_steps
        INTEGER,PUBLIC :: nzone_fp,nthrf,nubeam_nclass
        INTEGER,PUBLIC :: nefpdep,nxfpdep
        INTEGER,PUBLIC :: nseed,lunnbx,lunres
        INTEGER,PUBLIC :: mrstrt, nsigexc
        INTEGER,PUBLIC :: nptcls,nptclf,ndep0
        INTEGER,PUBLIC :: nmsigx,nkdifb,nrip,nsdbgb
        INTEGER,PUBLIC :: nxbox,nybox,nlbox,ndepbox
        INTEGER,PUBLIC :: nzones,avg_nubeam_torque
        INTEGER,PUBLIC :: xp_axi,xp_inr,xp_inz,xp_ierr,xp_nt1
        INTEGER,PUBLIC :: xp_rho_grid_size,xp_psi_grid_size ! size of rho
                                              !and psi  grid generated by
                                              ! call to eqm_fromgeqdsk 
        INTEGER,PUBLIC :: xp_got,xp_nj
        INTEGER,PUBLIC :: xp_magdim,xp_magfit,xp_cyldim
        INTEGER,PUBLIC :: id_rhonj,id_tflux
        INTEGER,PUBLIC :: xp_cylfit,xp_warn,xp_info,xp_npsi,xp_irz
        INTEGER,PUBLIC :: lcentr,ledge,lep1           !need to define these
                                                      !not used butr required
                                                      !for compilation for now.
        INTEGER,PUBLIC :: nubeam_evolve
        INTEGER,PUBLIC, DIMENSION(:),ALLOCATABLE :: nbsbox
        INTEGER,PUBLIC, DIMENSION(:),ALLOCATABLE :: nbebox
!
        !nubeam crashes if the time step is too small.
        !nubeam_dtmin is approximate minimum time interval that 
        !nubeam can handle allowed for nubeam
        REAL (DP) ,PARAMETER,PUBLIC :: nubeam_dtmin = 1.e-4
        REAL (DP) ,PUBLIC :: xp_fdy,xp_cbdy,xp_rho_axis,xp_rho_bdry
        REAL (DP) ,PUBLIC :: xp_tor_fluxt ,nubeam_on
        REAL (DP) ,PUBLIC :: nubeam_restart_time
        REAL (DP) ,PUBLIC ,DIMENSION(:),ALLOCATABLE     :: xp_tor_flux
        REAL (DP) ,PUBLIC ,DIMENSION(:),ALLOCATABLE     :: xp_rhonj
        REAL (DP) ,PUBLIC ,DIMENSION(:),ALLOCATABLE     :: xp_rho_grid
        REAL (DP) ,PUBLIC ,DIMENSION(:),ALLOCATABLE     :: xp_psi_grid
        REAL (DP) ,PUBLIC ,DIMENSION(:),ALLOCATABLE     :: xp_qval
        REAL (DP) ,PUBLIC ,DIMENSION(:),ALLOCATABLE     :: xp_psi_zone
        REAL (DP) ,PUBLIC ,DIMENSION(:),ALLOCATABLE     :: xp_rho_zone
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: aimpj
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: omegag
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: phiprg
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: curt
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: vpoh
        REAL (DP) ,PUBLIC, DIMENSION(:,:),ALLOCATABLE   :: omega_neut
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: efpdep
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: xfpdep
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: sscxl
!
!
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: qbth_nub
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: qbth_nubp
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: qbeame_nub
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: qbeami_nub
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: qbeame_nubp
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: qbeami_nubp
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: curb_nub
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: curb_nubp
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: storqueb_nub
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: storqueb_nubp
        REAL (DP) ,PUBLIC, DIMENSION(:,:), ALLOCATABLE  :: storque_nub_avg
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: sprbeame_nub
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: sprbeame_nubp
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: sprbeami_nub
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: sprbeami_nubp
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: wbeam_nub
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: wbeam_nubp
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: enbeam_nub
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: enbeam_nubp
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: beam_beamdtn_nub
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: beam_beamdtn_nubp
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: beam_beamddp_nub
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: beam_beamddp_nubp
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: beam_beamddn_nub
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: beam_beamddn_nubp
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: beam_beamtt2n_nub
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: beam_beamtt2n_nubp
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: beam_thermaltth_df_nub
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: beam_thermaltth_df_nubp
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: beam_thermalddp_nub
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: beam_thermalddp_nubp
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: beam_thermalddn_nub
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: beam_thermalddn_nubp
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: beam_thermaltt2n_nub
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: beam_thermaltt2n_nubp
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: beam_thermaldth_tf_nub
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: beam_thermaldth_tf_nubp

        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: sorbn0_nub !jmp.den
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: sorbn0_nubp !jmp.den
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: sorbh_nub !jmp.den
        REAL (DP) ,PUBLIC, DIMENSION(:),ALLOCATABLE     :: sorbh_nubp !jmp.den
!
!
!
        REAL (DP),PUBLIC :: qbeame_intg_nub,       qbeame_intg_nubp
        REAL (DP),PUBLIC :: qbeami_intg_nub,       qbeami_intg_nubp
        REAL (DP),PUBLIC :: qbth_intg_nub,         qbth_intg_nubp
        REAL (DP),PUBLIC :: curb_intg_nub,         curb_intg_nubp
        REAL (DP),PUBLIC :: storqueb_intg_nub,     storqueb_intg_nubp
        REAL (DP),PUBLIC :: sprbeame_intg_nub,     sprbeame_intg_nubp
        REAL (DP),PUBLIC :: sprbeami_intg_nub,     sprbeami_intg_nubp
        REAL (DP),PUBLIC :: wbeam_intg_nub,        wbeam_intg_nubp
        REAL (DP),PUBLIC :: enbeam_intg_nub,       enbeam_intg_nubp
!
        REAL (DP),PUBLIC :: pwf_tot_intg_nub,       pwf_tot_intg_nubp
        REAL (DP),PUBLIC :: beam_thermal_tt2ntot_nub
        REAL (DP),PUBLIC :: beam_thermal_tt2ntot_nubp
        REAL (DP),PUBLIC :: beam_thermal_ddptot_nub
        REAL (DP),PUBLIC :: beam_thermal_ddptot_nubp
        REAL (DP),PUBLIC :: beam_thermal_ddntot_nub
        REAL (DP),PUBLIC :: beam_thermal_ddntot_nubp
        REAL (DP),PUBLIC :: beam_thermal_dtntot_nub
        REAL (DP),PUBLIC :: beam_thermal_dtntot_nubp
        REAL (DP),PUBLIC :: beam_beam_tt2ntot_nub
        REAL (DP),PUBLIC :: beam_beam_tt2ntot_nubp
        REAL (DP),PUBLIC :: beam_beam_ddptot_nub
        REAL (DP),PUBLIC :: beam_beam_ddptot_nubp
        REAL (DP),PUBLIC :: beam_beam_ddntot_nub
        REAL (DP),PUBLIC :: beam_beam_ddntot_nubp
        REAL (DP),PUBLIC :: beam_beam_dtntot_nub
        REAL (DP),PUBLIC :: beam_beam_dtntot_nubp
!
        REAL (DP),PUBLIC :: goocon,gflr_min,nubeam_dt,nubeam0_dt
        REAL (DP),PUBLIC :: nubeam_back_delt,nubeam_fix_t,nubeam_back_average !JMP
        INTEGER,PUBLIC :: ifix_nubeam_dt !JMP
        REAL (DP),PUBLIC :: plfhe3,plfhe4,plfst,plfsp
        REAL (DP),PUBLIC :: cxsplt,dxbsmoo, wghta,dn0out
        REAL (DP),PUBLIC :: cxpcon,fppcon,dtn_orbit,xdepmod
        REAL (DP),PUBLIC :: xcfanbi,xdfanbi,xefanbi,xcfafus,xdfafus
        REAL (DP),PUBLIC :: xefafus
        REAL (SP),PUBLIC :: taurip,asrd,bsrd
        REAL (SP),PUBLIC :: fbemin,fbemax,fvpvmn,fshper,fshwid
        REAL (SP),PUBLIC :: tfshon,tfshof,fvpvmx,fbltim
        REAL (SP),PUBLIC :: xboxhw,yboxhw,xlbox1,xlbox2
        REAL (DP),PUBLIC :: plhgt,wrt_restart_file_time
        REAL (SP),PUBLIC :: edbfac,tbm1,tbm2,tsaw,dtmint
        REAL (DP),PUBLIC :: xdatsfa, xdatsf3, xdatsft,xdatsfp
        REAL (SP),PUBLIC :: CPXPGL,ZTIM2,ZTIM1
        REAL (SP),PUBLIC :: dt_nubeam_mult
        !fidffbe and edifbe are not allocatable because they
        !are namelist inputs:
        REAL (DP),PUBLIC, DIMENSION(ndifbep) :: fdifbe 
        REAL (DP),PUBLIC, DIMENSION(ndifbep) :: edifbe
!
!
        REAL (SP),PUBLIC, DIMENSION(:),ALLOCATABLE :: erngfi
        REAL (SP),PUBLIC, DIMENSION(15) :: gflr_op
        REAL (SP),PUBLIC, DIMENSION(:),ALLOCATABLE :: xzimpj
        REAL (SP),PUBLIC, DIMENSION(:),ALLOCATABLE :: tmjsm
        REAL (SP),PUBLIC, DIMENSION(:),ALLOCATABLE :: fracmini
        REAL (DP),PUBLIC, DIMENSION(:),POINTER :: nubeam_calls
!
!
        REAL (SP),PUBLIC, DIMENSION(:,:),ALLOCATABLE :: rhmin
        REAL (SP),PUBLIC, DIMENSION(:,:),ALLOCATABLE :: rhi



        REAL (DP) ,PUBLIC, DIMENSION(:,:),ALLOCATABLE     :: enbeam_species
        REAL (DP) ,PUBLIC, DIMENSION(:,:),ALLOCATABLE     :: enbeam_species_p
        REAL (DP) ,PUBLIC, DIMENSION(:,:),ALLOCATABLE     :: enbeam_species_c
!
        REAL (SP),PUBLIC,  DIMENSION(:),ALLOCATABLE :: xzmini
        REAL (SP),PUBLIC,  DIMENSION(:),ALLOCATABLE :: amini
        REAL (SP),PUBLIC, DIMENSION(:,:,:),ALLOCATABLE :: den0mn
        REAL (SP),PUBLIC, DIMENSION(:,:,:),ALLOCATABLE :: en0mn
        REAL (SP),PUBLIC, DIMENSION(:,:,:),ALLOCATABLE :: omg0mn
        REAL (SP),PUBLIC, DIMENSION(:,:,:),ALLOCATABLE :: rhbs
        REAL (SP),PUBLIC, DIMENSION(:,:,:),ALLOCATABLE :: rhix
!
!
       TYPE(neutral_beam),PUBLIC  :: beam_data
!
!

!
!
       TYPE(fidif),PUBLIC :: d_fast_ion
!
!
       DATA nubeam_steps /1/      !nubeam  restart files is created  on all calls
                                  !to nubeam. But The restart files are
                                  !read only if nubeam_steps >  1.
!
       DATA nubeam_root         /'nubeam_12'/
       DATA profile_save_file   /'none' /
       DATA state_save_file     /'none' / 
       DATA  xplasma_save_file  /'none' /
       DATA nubeam_init         /.FALSE./

!      Turn off fast ion diffusion:
       DATA d_fast_ion%adiff_0, d_fast_ion%adiff_a,               &
             d_fast_ion%adiff_xpin,d_fast_ion%adiff_xpout,        &
             d_fast_ion%fidif_on,d_fast_ion%ndifbe                &
             /0.0,0.0,0.0,0.0,0,0/



   END MODULE TRANSP
