[GYRO MPI tasks: 2]
[Parsing data in INPUT]
----------------------------------------------------------
INFO: Rotation effects with delta B_parallel are experimental.
----------------------------------------------------------
 -----------------------------------------------
 operational mode     : FIELD EIGENVALUE
 boundary conditions  : PERIODIC
 profiles             : FLAT
 geometry             : MODEL SHAPE
 electron_method      : ALL SPECIES GYROKINETIC
 fluctuations         : EM: (Phi,A_par,B_par)
 gyro_method          : GRID-BASED J0^2 POLARIZATION
 fluctuation output   : PHI( ) N( ) E( ) V( )                   
 radial grid          : UNIFORM
 energy_method        : CONSTANT
 integrator_method    : RK2
 field solve          : UMFPACK (SEQUENTIAL)
 source_flag          : SOURCE OFF
 pitch-angle coll.    : OFF
 rotation effects     : CANDY METHOD
 nonlinear dynamics   : OFF
 linear diffusivity   : OFF
 -----------------------------------------------
----------------------------------------------------------
INFO: Forcing up-down symmetry (UDSYMMETRY_FLAG=1).
----------------------------------------------------------
----------------------------------------------------------
INFO: You are using TOROIDAL_REFERENCE=-1
----------------------------------------------------------
----------------------------------------------------------
INFO: TOROIDAL_REFERENCE reset to lowest nonzero mode.
----------------------------------------------------------
----------------------------------------------------------
INFO: nu_ii rescaled by: 0.000
----------------------------------------------------------
 ----------- SPARSE MATRIX STATS ---------------
   POISSON-AMPERE:     n>0           
         nonzeros:     4096
           values:    12352
          indices:    16513
       iterations:        1

  EXPLICIT AMPERE:     n>0           
         nonzeros:     1024
           values:     3104
          indices:     4161
       iterations:        1

 ----------- UTILITY PARAMETERS ----------------
 Ion parallel motion     : ON
 Ion curvature drift     : ON
 Electron curvature drift: ON
 ----------- GRID DIMENSIONS -------------------
 n_n                  :    1
 n_x                  :    4
 n_stack              :   28
 n_blend              :    8
 n_pass               :    4
 n_trap               :    4
 n_energy             :    8
 n_field              :    3
 --
 n_spec               :    2
 n_ion                :    2
 n_kinetic            :    2
 n_gk                 :    2
 indx_e               :    2
 --
 FIELD POINTS:        :        96
 DIST. POINTS:        :     14336
 --
 energy_max           :   6.000000
 dt                   :   0.200000
 --------------- LOCAL PARAMETERS ---------------
 # RADIUS [INPUT]     :   0.700000
 .RADIUS              :   0.700000
 .ASPECT_RATIO        :   1.650000
 .SHIFT               :  -0.375000
 .ZMAG                :   0.000000
 .DZMAG               :   0.000000
 .KAPPA               :   2.400000
 .S_KAPPA             :  -0.120000
 .DELTA               :   0.310000
 .S_DELTA             :   0.230000
 .ZETA                :   0.000000
 .S_ZETA              :   0.000000
 .SAFETY_FACTOR       :   3.000000
 .SHEAR               :   0.880000
 .RHO_STAR            :   0.001944
 .Z_EFF               :   1.000000
 .MACH                :   0.000000
 .PGAMMA              :   0.000000
 .GAMMA_E             :   0.000000
 .LAMBDA_DEBYE        :   0.000000
 .NU_EI               :   0.000000
 .NU_I_KROOK          :   0.000000
 # Ion  1
 .NI_OVER_NE          :   1.000000
 .TI_OVER_TE          :   1.000000
 .DLNNDR              :   1.000000
 .DLNTDR              :   1.000000
 .Z                   :   1.000000
 (NU_II)              :   0.000000
 .MU                  :   1.000000
 # Electrons
 .DLNNDR_ELECTRON     :   1.000000
 .DLNTDR_ELECTRON     :   1.000000
 (Z_ELECTRON)         :  -1.000000
 .BETAE_UNIT          :   0.017000
 .MU_ELECTRON         :  60.000000
 -------- LOCAL PARAMETERS (diagnostic) ----------
 n_i*z_i - n_e:       :   0.000000
 r/R0                 :   0.424242
 beta_unit_norm       :   0.034000
 betai_unit           :   0.017000
 betae_unit_norm      :   0.017000
 beta_prime           :   0.068000
 omega_eb_0 (c_s/a)   :   0.000000
 * Note that f = f_sim exp(-i n omega_eb_0 t)
 -------- ALFVEN WAVE PARAMETERS (diagnostic) ----------
 (v_A/c_s)            :  10.845017
 Omega_A              :   1.095456
 ----------- UPWIND PARAMETERS -----------------
 radial_upwind        :   1.000000
 orbit_upwind         :   1.000000
 orbit_upwind (elec)  :   0.000000
 ----------- SOURCE PARAMETERS -----------------
 nu_source            :   0.100000
 n_source             :    1
 ----------- RADIAL DOMAIN PARAMETERS ----------
 s_grid               :   0.880000
 box_multiplier       :   1.000000
 L/a                  :   0.008838
 --
 explicit_damp(i)     :   0 (  1.0000)
 explicit_damp(e)     :   0 (  1.0000)
 --
 offset               :   0 (  0.0000)
 LEFT : r_a           :   0.695581
 LEFT : r_a_physical  :   0.695581
 NORM : r(ir_norm)    :   0.700000
 RIGHT: r_b_physical  :   0.702210
 RIGHT: r_b           :   0.702210
 ----------- PARALLELIZATION PARAMETERS --------
 (nek) per subgroup:  :        32
 (ine) per subgroup:  :        16
 ----------- TIME STEPPING PARAMETERS ----------
 plot_filter          :   1.000000
 time_skip            :     5
 restart_data_skip    :    10
 ----------- COURANT PARAMETERS ----------------
 max(THETA COURANT)   :  23.253966
 max(D1 COURANT)      :   0.755937
 max(DR COURANT)      :   1.431419
 ----------- SETUP TIMING ----------------------
 Grid Setup           :   0.041612
 Build radial ops     :   0.015184
 Build advection ops  :   0.000000
 Build field matrices :   0.247905

 TOTAL SETUP          :   0.355276
 ------ CENTRAL WAVENUMBERS SIMULATED -----------
 n =    30   k_theta rho_s = 0.250 [0.250][0.250]
 min(k_x*rho_s)       :     1.382301
 max(k_x*rho_s)       :     1.382301
 ------------- CENTRAL BOX SIZE -----------------
 Lx/rho_s             :     4.545455
 Ly/rho_s             :    25.132741
 => dx/rho_s          :     1.136364
 ------------------------------------------------
 ---------- GYRO-OPERATOR BANDWIDTH -------------
 => EXACT BESSEL.
 ------------------------------------------------
 PLEASE SEE: 
  - units.out for normalizing parameters
  - alloc.out for memory usage
  - efficiency.out for parallelization efficiency
  - phase_space.out for velocity-space nodes and weights
 STATUS: clean exit                                                                      
