#!/usr/bin/env python
"""
  Class with members and methods associated with parsing the "ITER DB
  Files"
"""

iterDBmap={}
iterDBmap['psi on rho grid']="psi"
iterDBmap['rho grid']="rho"
iterDBmap['electron temperature']="temperature_electron"
iterDBmap['ion temperatue']="temperature_ion"
iterDBmap['total current density']="currentDensity_total"
iterDBmap['ohmic current density']="currentDensity_ohmic"
iterDBmap['bootstrap current density']="currentDensity_bootstrap"
iterDBmap['beam-driven current density']="currentDensity_beams"
iterDBmap['RF current density']="currentDensity_RF"
iterDBmap['rho*bp0*fcap*gcap*hcap']="rho*bp0*fcap*gcap*hcap"
iterDBmap['angular rotation speed profile']="omega"
iterDBmap['electron conduction']="powerConduction_electron"
iterDBmap['ion conduction']="energyConduction_ion"
iterDBmap['electron convection']="energyConvection_electron"
iterDBmap['ion convection']="energyConvection_ion"
iterDBmap['electron thermal diffusivity']="thermalDiffusivity_electron"
iterDBmap['ion thermal diffusivity']="thermalDiffusivity_ion"
iterDBmap['ion neoclassical thermal conductivity']="thermalConductivityNeoclassical_ion"
iterDBmap['power to elec. from beam']="qbeame"
iterDBmap['power to ions from beam']="qbeami"
iterDBmap['2d electron heating']="qe2d"
iterDBmap['2d ion heating']="qi2d"
iterDBmap['fusion electron heating']="qalpha_electron"
iterDBmap['fusion ion heating']="qalpha_ion"
iterDBmap['beam fusion electron heating']="qbeamFusion_electron"
iterDBmap['beam fusion ion heating']="qbeamFusion_electron"
iterDBmap['qmag electron heating']="qmage"
iterDBmap['sawtooth electron heating']="qsawe"
iterDBmap['sawtooth ion  heating']="qsawi"
iterDBmap['radiated power density']="qrad"
iterDBmap['(electron) ohmic power density']="qohmic"
iterDBmap['average major radius of each flux surface']="radiusMajor"
iterDBmap['average minor radius of each flux surface']="radiusMinor"
iterDBmap['volume of each flux surface']="volume"
iterDBmap['elongation of each flux surface']="elongation"
iterDBmap['triangularity of each flux surface']="triangularity"
iterDBmap['indentation of each flux surface']="indentation"
iterDBmap['surface area of each flux surface']="surfaceArea"
iterDBmap['cross-sectional area of each flux surface']="crossSectionalArea"
iterDBmap['flux surface average absolute grad rho']="gradRho"
iterDBmap['flux surface average (grad rho)**2']="gradRhoSq"
iterDBmap['r points for plasma boundary']="rBound"
iterDBmap['z points for plasma boundary']="zBound"
iterDBmap['beam   torque density']="torqueDensityBeam"
iterDBmap['electron density']="density_electron"
iterDBmap['4*pi*pi*R0*hcap*rho*<ABS(grad rho)>']="4*pi*pi*R0*hcap*rho*<ABS(grad rho)>"
iterDBmap['primary ion density']="density_ion"
iterDBmap['impurity ion density']="density_impurity"
iterDBmap['fast ion density']="density_fastIon"
iterDBmap['neutral density']="density_neutral"
iterDBmap['neutral density from wall source']="density_neutralWall"
iterDBmap['neutral density from volume source']="density_neutralVolume"
iterDBmap['volume source of neutrals']="densitySourceVolume"
iterDBmap['zeff profile']="zeff"
iterDBmap['safety factor']="qSafetyFactor"
