      complex*16 kpar_gp1,kpar_gr11,kpar_gr13,kpar_gu1,kpar_gu3
      complex*16 kpar_gb1,kpar_gb3,kpar_gb33
      complex*16 kpar_gb1gt1,kpar_gb3gt3,kpar_gb33gt1
      real*8 modkpar_gd1,modkpar_gd3,modkpar_gd33
      real*8 modkpar_gd1gu1,modkpar_gd3gu3,modkpar_gd33gu1
      real*8 modkpar_gu1,modkpar_gu3
      real*8 ave_kpargp1(ns,nb,nb),ave_kpargr11(ns,nb,nb)
      real*8 ave_kpargr13(ns,nb,nb)
      real*8 ave_kpargu1(ns,nb,nb),ave_kpargu3(ns,nb,nb)
      real*8 ave_kpargt1(ns,nb,nb),ave_kpargt3(ns,nb,nb)
      real*8 ave_modkpargu1(ns,nb,nb),ave_modkpargu3(ns,nb,nb)
      common /kparg/
     > kpar_gp1,kpar_gr11,kpar_gr13,kpar_gu1,kpar_gu3,
     > kpar_gb1,kpar_gb3,kpar_gb33,
     > kpar_gb1gt1,kpar_gb3gt3,kpar_gb33gt1,
     > modkpar_gd1,modkpar_gd3,modkpar_gd33,
     > modkpar_gd1gu1,modkpar_gd3gu3,modkpar_gd33gu1,
     > modkpar_gu1,modkpar_gu3,
     > ave_kpargp1,ave_kpargr11,ave_kpargr13,
     > ave_kpargu1,ave_kpargu3,
     > ave_kpargt1,ave_kpargt3,ave_modkpargu1,ave_modkpargu3
