      complex*16 kpar_hp1,kpar_hr11,kpar_hr13,kpar_hu1,kpar_hu3
      complex*16 kpar_hb1,kpar_hb3,kpar_hb33
      complex*16 kpar_hb1ht1,kpar_hb3ht3,kpar_hb33ht1
      real*8 modkpar_hd1,modkpar_hd3,modkpar_hd33
      real*8 modkpar_hd1hu1,modkpar_hd3hu3,modkpar_hd33hu1
      real*8 modkpar_hu1,modkpar_hu3
      real*8 ave_kparhp1(ns,nb,nb),ave_kparhr11(ns,nb,nb)
      real*8 ave_kparhr13(ns,nb,nb)
      real*8 ave_kparhu1(ns,nb,nb),ave_kparhu3(ns,nb,nb)
      real*8 ave_kparht1(ns,nb,nb),ave_kparht3(ns,nb,nb)
      real*8 ave_modkparhu1(ns,nb,nb),ave_modkparhu3(ns,nb,nb)
      common /kparh/
     > kpar_hp1,kpar_hr11,kpar_hr13,kpar_hu1,kpar_hu3,
     > kpar_hb1,kpar_hb3,kpar_hb33,
     > kpar_hb1ht1,kpar_hb3ht3,kpar_hb33ht1,
     > modkpar_hd1,modkpar_hd3,modkpar_hd33,
     > modkpar_hd1hu1,modkpar_hd3hu3,modkpar_hd33hu1,
     > modkpar_hu1,modkpar_hu3,
     > ave_kparhp1,ave_kparhr11,ave_kparhr13,
     > ave_kparhu1,ave_kparhu3,
     > ave_kparht1,ave_kparht3,ave_modkparhu1,ave_modkparhu3
