[GYRO MPI tasks: 2]
[Parsing data in INPUT]
 -----------------------------------------------
 boundary conditions  : PERIODIC
 profiles             : FLAT
 geometry             : S-ALPHA
 electron_method      : ADIABATIC ELECTRONS
 fluctuations         : ELECTROSTATIC
 gyro_method          : ORIGINAL (INTEGRATED) POLARIZATION
 fluctuation output   : PHI( ) N( ) E( ) V( )                   
 radial grid          : UNIFORM
 energy_method        : CONSTANT
 integrator_method    : RK2
 field solve          : UMFPACK (SEQUENTIAL)
 source_flag          : SOURCE OFF
 pitch-angle coll.    : OFF
 rotation effects     : CANDY METHOD
 nonlinear dynamics   : ON
 nonlinear bracket    : DIRECT
 -----------------------------------------------
----------------------------------------------------------
INFO: Forcing up-down symmetry (UDSYMMETRY_FLAG=1).
----------------------------------------------------------
----------------------------------------------------------
INFO: You are using TOROIDAL_REFERENCE=-1
----------------------------------------------------------
----------------------------------------------------------
INFO: TOROIDAL_REFERENCE reset to lowest nonzero mode.
----------------------------------------------------------
----------------------------------------------------------
INFO: nu_ii rescaled by: 0.000
----------------------------------------------------------
----------------------------------------------------------
INFO: nu_ei rescaled by: 0.000
----------------------------------------------------------
 ----------- SPARSE MATRIX STATS ---------------
 EXPLICIT POISSON:     n=0        n>0
         nonzeros:     4824      5184
           values:    17016     15624
          indices:    21896     23336
       iterations:        1         1

 ----------- UTILITY PARAMETERS ----------------
 Ion parallel motion     : ON
 Ion curvature drift     : ON
 Electron curvature drift: ON
 ----------- GRID DIMENSIONS -------------------
 n_n                  :    2
 n_x                  :   12
 n_stack              :   20
 n_blend              :    6
 n_pass               :    4
 n_trap               :    4
 n_energy             :    8
 n_field              :    1
 --
 n_spec               :    2
 n_ion                :    1
 n_kinetic            :    1
 n_gk                 :    1
 indx_e               :    2
 --
 FIELD POINTS:        :       144
 DIST. POINTS:        :     30720
 --
 energy_max           :   6.000000
 dt                   :   0.100000
 --------------- LOCAL PARAMETERS ---------------
 # RADIUS [INPUT]     :   0.500000
 .RADIUS              :   0.500000
 .ASPECT_RATIO        :   3.000000
 .SHIFT               :   0.000000
 .ZMAG                :   0.000000
 .DZMAG               :   0.000000
 .KAPPA               :   1.000000
 .S_KAPPA             :   0.000000
 .DELTA               :   0.000000
 .S_DELTA             :   0.000000
 .ZETA                :   0.000000
 .S_ZETA              :   0.000000
 .SAFETY_FACTOR       :   2.000000
 .SHEAR               :   1.000000
 .RHO_STAR            :   0.002500
 .Z_EFF               :   1.000000
 .MACH                :   0.000000
 .PGAMMA              :   0.000000
 .GAMMA_E             :   0.000000
 .LAMBDA_DEBYE        :   0.000000
 .NU_EI               :   0.000000
 .NU_I_KROOK          :   0.000000
 # Ion  1
 .NI_OVER_NE          :   1.000000
 .TI_OVER_TE          :   1.000000
 .DLNNDR              :   1.000000
 .DLNTDR              :   3.000000
 .Z                   :   1.000000
 (NU_II)              :   0.000000
 .MU                  :   1.000000
 -------- LOCAL PARAMETERS (diagnostic) ----------
 n_i*z_i - n_e:       :   0.000000
 r/R0                 :   0.166667
 beta_unit_norm       :   0.000000
 betai_unit           :   0.000000
 betae_unit_norm      :   0.000000
 omega_eb_0 (c_s/a)   :   0.000000
 * Note that f = f_sim exp(-i n omega_eb_0 t)
 ----------- UPWIND PARAMETERS -----------------
 radial_upwind        :   1.000000
 orbit_upwind         :   1.000000
 ----------- SOURCE PARAMETERS -----------------
 nu_source            :   0.100000
 n_source             :    1
 ----------- RADIAL DOMAIN PARAMETERS ----------
 s_grid               :   1.000000
 box_multiplier       :   5.000000
 L/a                  :   0.062500
 --
 explicit_damp(i)     :   0 (  1.0000)
 explicit_damp(e)     :   0 (  1.0000)
 --
 offset               :   0 (  0.0000)
 LEFT : r_a           :   0.468750
 LEFT : r_a_physical  :   0.468750
 NORM : r(ir_norm)    :   0.500000
 RIGHT: r_b_physical  :   0.526042
 RIGHT: r_b           :   0.526042
 ----------- PARALLELIZATION PARAMETERS --------
 (nek) per subgroup:  :        64
 (ine) per subgroup:  :        96
 ----------- TIME STEPPING PARAMETERS ----------
 plot_filter          :   1.000000
 time_skip            :    10
 restart_data_skip    :    10
 ----------- COURANT PARAMETERS ----------------
 max(THETA COURANT)   :   0.087854
 max(D1 COURANT)      :   0.115702
 max(DR COURANT)      :   0.175660
 ----------- SETUP TIMING ----------------------
 Grid Setup           :   0.143668
 Build radial ops     :   0.059931
 Build advection ops  :   0.000000
 Build field matrices :   0.255914

 TOTAL SETUP          :   0.502862
 ------ CENTRAL WAVENUMBERS SIMULATED -----------
 n =     0   k_theta rho_s = 0.000 [0.000][0.000]
 n =    20   k_theta rho_s = 0.200 [0.200][0.200]
 min(k_x*rho_s)       :     0.251327
 max(k_x*rho_s)       :     0.753982
 ------------- CENTRAL BOX SIZE -----------------
 Lx/rho_s             :    25.000000
 Ly/rho_s             :    31.415927
 => dx/rho_s          :     2.083333
 ------------------------------------------------
 ---------- GYRO-OPERATOR BANDWIDTH -------------
 => EXACT BESSEL.
 ------------------------------------------------
 PLEASE SEE: 
  - units.out for normalizing parameters
  - alloc.out for memory usage
  - efficiency.out for parallelization efficiency
  - phase_space.out for velocity-space nodes and weights
 STATUS: clean exit                                                                      
