#---------------------------------------------------------------
# Toplevel makefile for pneo: must be executed from gacode/neo
#---------------------------------------------------------------

include ${GACODE_ROOT}/platform/build/make.inc.${GACODE_PLATFORM}

all:
	cd src ; make

clean:
	cd src ; make clean

.IGNORE:
