#!/bin/bash

# Comment Information
TITLE="CGYRO Turbulence"
TIMESTAMP=`date`

# Main movie definitions
BASENAME=%03d.png
BITRATE=1000k
FRAMERATE=20
QUALITY=19
OUT=movie.mp4

avconv -framerate $FRAMERATE \
    -i $BASENAME \
    -c:v libx264 \
    -profile:v high \
    -crf $QUALITY \
    -pix_fmt yuv420p \
    -metadata title="$TITLE" \
    -metadata creation_time="$TIMESTAMP" \
    $OUT
