#!/bin/bash

# Comment Information
TITLE="CGYRO Turbulence"
TIMESTAMP=`date -Iseconds`

START=$1
FRAMERATE=$2
QUALITY=$3
PRE=$4

# Main movie definitions
BASENAME=$PRE%d.png
OUT=${PRE}movie.mp4

if hash avconv 2>/dev/null ; then
    avconv -framerate $FRAMERATE \
	   -start_number $1 \
	   -i $BASENAME \
	   -c:v libx264 \
	   -pix_fmt yuv420p \
	   -metadata title="$TITLE" \
	   -metadata creation_time="$TIMESTAMP" \
	   -crf $QUALITY $OUT
elif hash ffmpeg 2>/dev/null ; then
    ffmpeg -framerate $FRAMERATE \
	   -start_number $1 \
	   -i $BASENAME \
	   -c:v libx264 \
	   -pix_fmt yuv420p \
	   -metadata title="$TITLE" \
	   -metadata creation_time="$TIMESTAMP" \
	   -crf $QUALITY $OUT
else
    echo Need avconv or ffmpeg in gacode/python/cgyro/avconv_wrapper
fi
