#!/bin/sh
# Setup transp2gyro @ PPPL

# Module for transp tools. As of 12/2009 no longer need grid access
module load ntcc

# Variabls for MDS+ access
setenv MDS_TRANSP_SERVER transpgrid.pppl.gov

# For python
module load python/2.6.3
setenv PYTHON_COMMAND python

