#!/bin/bash

nvec="3 4 5 6 7 8 9 10 11 12"
evec="5 6 8 10 12"

for n in $nvec
do
   for e in $evec
   do
      python $GACODE_ROOT/shared/math/gauss_exp_quad.py $e $n 0
      OUT=egrid.$n.$e
      mv out.cgyro.egrid $OUT
      echo "Created $OUT"
   done
done
