!-------------------------------------------------------------------------
! glf23_interface.f90
!
! PURPOSE:
!  Provides interface description for GLF23.
!
! CALLING SEQUENCE:
!  call glf23_init(...)
!  set glf23_*_in variables
!  call glf23_run(...)
!  get glf23_*_out variables
!
! NOTES:
!  glf23_path:        working directory 
!  glf23_dump_flag:   TRUE = call dump routines, FALSE = do NOT call dump routines
!  glf23_dump_suffix: appended to name of dump file
!
!  glf23_dump_local and glf23_dump_global are called by glf23_run
!
! NAMING CONVENTION:
!  Interface parameter names are formed from GLF23 variable names by 
!  prepending 'glf23_' and appending '_in'
!
! INITIALIZATION:
!  We initialize input arrays/vectors to zero 
!
!-------------------------------------------------------------------------

module glf23_interface

  implicit none
! maximum dimensions
  integer,parameter :: nsm=6
  integer,parameter :: maxmodes=4

  ! CONTROL PARAMETERS
  character (len=256)  :: glf23_path_in        = ''
  logical              :: glf23_dump_flag_in   = .false.
  logical              :: glf23_quiet_flag_in  = .true.

  ! INPUT PARAMETERS

  logical :: glf23_use_transport_model_in = .true.
  !  Data passed to: put_model_parameters
  real    :: glf23_alpha_p_in        = 1.0
  real    :: glf23_alpha_quench_in   = 1.0
  integer :: glf23_version_in = 3

  ! Data passed to: put_species
  integer :: glf23_ns_in             = 2
  real    :: glf23_mass_in(nsm)      = 0.0
  real    :: glf23_zs_in(nsm)        = 0.0

  ! Data passed to: put_kys
  real    :: glf23_ky_in             = 0.3

  ! Data passed to: put_gradients
  real    :: glf23_rlns_in(nsm)      = 0.0
  real    :: glf23_rlts_in(nsm)      = 0.0
  real    :: glf23_vpar_shear_in(nsm)= 0.0
  real    :: glf23_vexb_shear_in     = 0.0

  ! Data passed to: put_averages
  real    :: glf23_taus_in(nsm)    = 0.0
  real    :: glf23_as_in(nsm)      = 0.0
  real    :: glf23_betae_in        = 0.0
  real    :: glf23_xnue_in         = 0.0

  ! Data passed to: put_s_alpha_geometry
  real    :: glf23_rmin_sa_in        = 0.5
  real    :: glf23_rmaj_sa_in        = 3.0
  real    :: glf23_q_sa_in           = 2.0
  real    :: glf23_shat_sa_in        = 1.0
  real    :: glf23_alpha_sa_in       = 0.0
  real    :: glf23_xwell_sa_in       = 0.0
  real    :: glf23_theta0_sa_in      = 0.0


  ! TRANSPORT OUTPUT PARAMETERS
  real :: glf23_elec_pflux_out = 0.0
  real :: glf23_elec_eflux_out = 0.0
  real :: glf23_elec_eflux_low_out = 0.0
  real :: glf23_elec_mflux_out = 0.0
  real :: glf23_elec_expwd_out = 0.0

  real, dimension(nsm-1) :: glf23_ion_pflux_out = 0.0
  real, dimension(nsm-1) :: glf23_ion_eflux_out = 0.0
  real, dimension(nsm-1) :: glf23_ion_eflux_low_out = 0.0
  real, dimension(nsm-1) :: glf23_ion_mflux_out = 0.0
  real, dimension(nsm-1) :: glf23_ion_expwd_out = 0.0
  
  ! LINEAR OUTPUT PARAMETERS
  complex :: glf23_eigenvalue_out(maxmodes)
  REAL,EXTERNAL :: get_growthrate
  REAL,EXTERNAL :: get_frequency
  REAL,EXTERNAL :: get_particle_flux
  REAL,EXTERNAL :: get_energy_flux
  REAL,EXTERNAL :: get_stress_tor
  REAL,EXTERNAL :: get_stress_par
  REAL,EXTERNAL :: get_exchange
  
  ! ERROR OUTPUT
  character (len=80) :: glf23_error_message='null'
  integer :: glf23_error_status=0

contains

  ! Dump LOCAL INTERFACE variables
  subroutine glf23_dump_local()

    implicit none

    integer :: ierr, i

    open(unit=1,file=trim(glf23_path_in)//'out.glf23.localdump',&
         status='replace',iostat=ierr)

    write(1,*) '# input.glf23 generated by glf23_dump_local()'
    write(1,*) '#'
    write(1,*) '# See https://fusion.gat.com/theory/glf23input'
    write(1,*) ' '
    write(1,*) '#---------------------------------------------------'
    write(1,*) '# Control parameters:'
    write(1,*) '#---------------------------------------------------'
    write(1,10) 'USE_TRANSPORT_MODEL',glf23_use_transport_model_in
    write(1,30) 'ALPHA_P',glf23_alpha_p_in
    write(1,30) 'ALPHA_QUENCH',glf23_alpha_quench_in
    write(1,20) 'VERSION',glf23_version_in
!
    write(1,30) 'KY',glf23_ky_in
    write(1,30) 'VEXB_SHEAR',glf23_vexb_shear_in
    write(1,30) 'BETAE',glf23_betae_in
    write(1,30) 'XNUE',glf23_xnue_in
    write(1,*) ' '
    write(1,*) '#---------------------------------------------------'
    write(1,*) '# Species vectors:'
    write(1,*) '#---------------------------------------------------'
    write(1,20) 'NS',glf23_ns_in
    do i = 1,glf23_ns_in
        write(1,40) 'ZS_',i,glf23_zs_in(i)
    enddo
    do i = 1,glf23_ns_in
        write(1,40) 'MASS_',i,glf23_mass_in(i)
    enddo
    do i = 1,glf23_ns_in
        write(1,40) 'RLNS_',i,glf23_rlns_in(i)
    enddo
    do i = 1,glf23_ns_in
        write(1,40) 'RLTS_',i,glf23_rlts_in(i)
    enddo
    do i = 1,glf23_ns_in
        write(1,40) 'TAUS_',i,glf23_taus_in(i)
    enddo
    do i = 1,glf23_ns_in
        write(1,40) 'AS_',i,glf23_as_in(i)
    enddo
    do i = 1,glf23_ns_in
        write(1,40) 'VPAR_SHEAR_',i,glf23_vpar_shear_in(i)
    enddo
    write(1,*) ' '
    write(1,*) '#---------------------------------------------------'
    write(1,*) '# s-alpha geometry parameters:'
    write(1,*) '#---------------------------------------------------'
    write(1,30) 'RMIN_SA',glf23_rmin_sa_in
    write(1,30) 'RMAJ_SA',glf23_rmaj_sa_in
    write(1,30) 'Q_SA',glf23_q_sa_in
    write(1,30) 'SHAT_SA',glf23_shat_sa_in
    write(1,30) 'ALPHA_SA',glf23_alpha_sa_in
    write(1,30) 'XWELL_SA',glf23_xwell_sa_in
    write(1,30) 'THETA0_SA',glf23_theta0_sa_in
    write(1,*) ' '

    close(1)

10  format(t2,a,'=',l1)
20  format(t2,a,'=',i3)
30  format(t2,a,'=',1pe12.5)
40  format(t2,a,i1,'=',1pe12.5)

  end subroutine glf23_dump_local

  ! Dump GLF23 MODULE variables
  subroutine glf23_dump_module()

    use glf23_gf

    implicit none

    integer :: ierr

    open(unit=1,file=trim(glf23_path_in)//'out.glf23.moduledump',&
         status='replace',iostat=ierr)

    write(1,*) 'ky = ', xky0_gf
    write(1,*) 'ns = ', ns_gf
    write(1,*) 'park = ', park_gf
    write(1,*) 'ghat = ', ghat_gf
    write(1,*) 'gchat = ', gchat_gf
    write(1,*) 'alpha_quench = ', alpha_e_gf
    write(1,*) 'alpha_p = ', alpha_p_gf
    write(1,*) 'betae = ', betae_gf
    write(1,*) 'xnuei = ', xnu_gf

    write(1,*)'mass_ion', amassgas_gf
    write(1,*) 'mass_imp = ', amassimp_gf
    write(1,*) 'zimp = ', zimp_gf
    write(1,*) 'rlne = ', rlne_gf
    write(1,*) 'rlte = ', rlte_gf
    write(1,*) 'rlni = ', rlni_gf
    write(1,*) 'rlti = ', rlti_gf
    write(1,*) 'vpar_shear = ', gamma_p_gf
    write(1,*) 'vexb_shear = ', gamma_e_gf
    write(1,*) 'awt = ', apwt_gf
    write(1,*) 'aiwt = ',aiwt_gf
    write(1,*) 'taui = ', taui_gf

    write(1,*) 'rmin_sa = ', rmin_gf
    write(1,*) 'rmaj_sa = ', rmaj_gf
    write(1,*) 'q_sa = ', q_gf
    write(1,*) 'shat_sa = ', shat_gf
    write(1,*) 'alpha_sa = ', alpha_gf
    write(1,*) 'xwell_sa = ', xwell_gf
    write(1,*) 'theta0_sa = ', theta0_gf

    close(1)

  end subroutine glf23_dump_module

end module glf23_interface
