[GYRO MPI tasks: 4]
[Parsing data in INPUT]
----------------------------------------------------------
INFO: Rotation effects with delta B_parallel are experimental.
----------------------------------------------------------
 -----------------------------------------------
 operational mode     : FIELD EIGENVALUE
 boundary conditions  : PERIODIC
 profiles             : FLAT
 geometry             : MODEL SHAPE
 electron_method      : ALL SPECIES GYROKINETIC
 fluctuations         : EM: (Phi,A_par,B_par)
 gyro_method          : ORIGINAL (INTEGRATED) POLARIZATION
 fluctuation output   : PHI(+) N( ) E( ) V( )                   
 radial grid          : UNIFORM
 energy_method        : CONSTANT
 integrator_method    : RK4
 field solve          : UMFPACK (SEQUENTIAL)
 source_flag          : SOURCE OFF
 pitch-angle coll.    : RBF r^3
 rotation effects     : CANDY METHOD
 nonlinear dynamics   : OFF
 linear diffusivity   : RESPONSE FUNCTION
 -----------------------------------------------
----------------------------------------------------------
INFO: Forcing up-down symmetry (UDSYMMETRY_FLAG=1).
----------------------------------------------------------
----------------------------------------------------------
INFO: You are using TOROIDAL_REFERENCE=-1
----------------------------------------------------------
----------------------------------------------------------
INFO: TOROIDAL_REFERENCE reset to lowest nonzero mode.
----------------------------------------------------------
----------------------------------------------------------
INFO: nu_ii rescaled by: 0.000
----------------------------------------------------------
 ----------- SPARSE MATRIX STATS ---------------
   POISSON-AMPERE:     n>0           
         nonzeros:     2304
           values:     6960
          indices:     9313
       iterations:        1

  EXPLICIT AMPERE:     n>0           
         nonzeros:      576
           values:     1752
          indices:     2353
       iterations:        1

 ----------- UTILITY PARAMETERS ----------------
 Ion parallel motion     : ON
 Ion curvature drift     : ON
 Electron curvature drift: ON
 ----------- GRID DIMENSIONS -------------------
 n_n                  :    1
 n_x                  :    4
 n_stack              :   20
 n_blend              :    6
 n_pass               :    4
 n_trap               :    4
 n_energy             :    8
 n_field              :    3
 --
 n_spec               :    2
 n_ion                :    2
 n_kinetic            :    2
 n_gk                 :    2
 indx_e               :    2
 --
 FIELD POINTS:        :        72
 DIST. POINTS:        :     10240
 --
 energy_max           :   6.000000
 dt                   :   0.005000
 --------------- LOCAL PARAMETERS ---------------
 # RADIUS [INPUT]     :   0.500000
 .RADIUS              :   0.500000
 .ASPECT_RATIO        :   3.000000
 .SHIFT               :   0.000000
 .ZMAG                :   0.000000
 .DZMAG               :   0.000000
 .KAPPA               :   1.000000
 .S_KAPPA             :   0.000000
 .DELTA               :   0.000000
 .S_DELTA             :   0.000000
 .ZETA                :   0.000000
 .S_ZETA              :   0.000000
 .SAFETY_FACTOR       :   2.000000
 .SHEAR               :   1.000000
 .RHO_STAR            :   0.050000
 .Z_EFF               :   1.000000
 .MACH                :   0.000000
 .PGAMMA              :   0.000000
 .GAMMA_E             :   0.000000
 .LAMBDA_DEBYE        :   0.000000
 .NU_EI               :   0.250000
 .NU_I_KROOK          :   0.000000
 # Ion  1
 .NI_OVER_NE          :   1.000000
 .TI_OVER_TE          :   1.000000
 .DLNNDR              :   1.000000
 .DLNTDR              :   3.000000
 .Z                   :   1.000000
 (NU_II)              :   0.000000
 .MU                  :   1.000000
 # Electrons
 .DLNNDR_ELECTRON     :   1.000000
 .DLNTDR_ELECTRON     :   6.000000
 (Z_ELECTRON)         :  -1.000000
 .BETAE_UNIT          :   0.020000
 .MU_ELECTRON         :  60.000000
 -------- LOCAL PARAMETERS (diagnostic) ----------
 n_i*z_i - n_e:       :   0.000000
 r/R0                 :   0.166667
 beta_unit_norm       :   0.040000
 betai_unit           :   0.020000
 betae_unit_norm      :   0.020000
 beta_*               :   0.220000
 alpha_MHD            :   2.640000
 omega_eb_0 (c_s/a)   :   0.000000
 * Note that f = f_sim exp(-i n omega_eb_0 t)
 -------- ALFVEN WAVE PARAMETERS (diagnostic) ----------
 (v_A/c_s)            :   9.998611
 Omega_A              :   0.833218
 ----------- UPWIND PARAMETERS -----------------
 radial_upwind        :   2.000000
 orbit_upwind         :   0.000000
 orbit_upwind (elec)  :   0.000000
 ----------- SOURCE PARAMETERS -----------------
 nu_source            :   0.100000
 n_source             :    1
 ----------- RADIAL DOMAIN PARAMETERS ----------
 s_grid               :   1.000000
 box_multiplier       :   1.000000
 L/a                  :   0.008333
 --
 explicit_damp(i)     :   0 (  1.0000)
 explicit_damp(e)     :   0 (  1.0000)
 --
 offset               :   0 (  0.0000)
 LEFT : r_a           :   0.495833
 LEFT : r_a_physical  :   0.495833
 NORM : r(ir_norm)    :   0.500000
 RIGHT: r_b_physical  :   0.502083
 RIGHT: r_b           :   0.502083
 ----------- PARALLELIZATION PARAMETERS --------
 (nek) per subgroup:  :        16
 (ine) per subgroup:  :         8
 ----------- TIME STEPPING PARAMETERS ----------
 plot_filter          :   1.000000
 time_skip            :    10
 restart_data_skip    :    10
 ----------- COURANT PARAMETERS ----------------
 max(THETA COURANT)   :   0.266352
 max(D1 COURANT)      :   0.157026
 max(DR COURANT)      :   0.442140
 ----------- SETUP TIMING ----------------------
 Grid Setup           :   0.084287
 Build radial ops     :   0.007613
 Build advection ops  :   0.000000
 Build field matrices :   0.088647

 TOTAL SETUP          :   0.214244
 ------ CENTRAL WAVENUMBERS SIMULATED -----------
 n =    30   k_theta rho_s = 6.000 [6.000][6.000]
 min(k_x*rho_s)       :    37.699112
 max(k_x*rho_s)       :    37.699112
 ------------- CENTRAL BOX SIZE -----------------
 Lx/rho_s             :     0.166667
 Ly/rho_s             :     1.047198
 => dx/rho_s          :     0.041667
 ------------------------------------------------
 ---------- GYRO-OPERATOR BANDWIDTH -------------
 => EXACT BESSEL.
 ------------------------------------------------
 PLEASE SEE: 
  - units.out for normalizing parameters
  - alloc.out for memory usage
  - efficiency.out for parallelization efficiency
  - phase_space.out for velocity-space nodes and weights
 STATUS: unconverged                                                                     
