#!/bin/sh
######################################################################
#
# File:		cleanconf.sh
#
# Purpose:	to remove autogenerated files
#
# Version:	$Id: cleanconf.sh 3366 2010-01-15 18:43:10Z dws $
#
# Copyright 2003-2010, Tech-X Corporation
#
######################################################################

# read command-line parameters
regenconf=true

while getopts an opt; do
  case "$opt" in
    a) echo "-a now the default.  Use -n to prevent regeneration.";;
    n) regenconf=false;;
   \?) # unknown flag
      echo >&2 "Usage: $0 [-n]"
      exit 1
      ;;
  esac
done
shift `expr $OPTIND - 1`

# Get rid of old files
echo Removing all the autogenerated files
cmd='rm -f configure config.cache aclocal.m4 config.h.in'
echo "$cmd"
eval $cmd
# cmd='(cd config; rm -f ltmain.sh)'
# echo "$cmd"
# eval $cmd

# Change to writeable for removal
chmod -R u+w .
# jrc 1nov08: some should not be removed
# rmfiles="Makefile.in Makefile.am.orig hdrs.txt cppsrcs.txt cxxsrcs.txt distfiles.txt"
rmfiles="Makefile.in Makefile.am.orig"
for i in $rmfiles; do
  dirrmfiles=`sed -e 's/dnl.*$//' -e 's/#.*$//' <configure.ac | grep Makefile$ | sed -e "s%(%%g" -e "s%)%%g" -e "s%\[%%g" -e "s%AC_CONFIG_FILES%%g" -e "s%Makefile$%$i%"`
  cmd="rm -f $dirrmfiles"
  echo $cmd
  $cmd
done

echo Removing configure cache
cmd="rm -rf autom4te.cache autom4te-*.cache"
echo "$cmd"
eval $cmd

# Creating new files for this platform
if ! $regenconf; then
  echo
  echo You should now make files specific to local versions of
  echo automake/autoconf by doing the following:
  echo "  config/regenconf.sh"
  echo or
  echo "  $0 (i.e., run this without the -n option)"
else
  configdir=`dirname $0`
  echo $configdir/regenconf.sh
  $configdir/regenconf.sh
  res=$?
  if test $res != 0; then
    exit $res
  fi
fi

echo Determining valid command-line options
./configure --help | egrep -- '--(enable|disable)' | grep -v FEATURE |\
  sed -e 's/  --enable-//' -e 's/  --disable-//' -e 's/-/_/g' \
    -e 's/\[.*\]//' -e 's/[ ].*$//' > .config.opts
./configure --help | egrep -- '--with' | grep -v FEATURE |\
  sed -e 's/  --with-//' -e 's/=.*$//' -e 's/-/_/g' \
    -e 's/[ ][ ]*.*$//' > .config.with

# Need to handle AC_CONFIG_SUBDIRS since cleanconf.sh not only does
# not handle those directories, but actually removes those directories
if grep "AC_CONFIG_SUBDIRS" < "configure.ac" > /dev/null 2>&1 ; then
  config_subdirs=`grep AC_CONFIG_SUBDIRS configure.ac | sed 's/.*\[//' | sed 's/\].*//'`
  echo $config_subdirs
  startdir=`pwd`
  for dir in $config_subdirs; do
    cd $dir
    echo "Running config/cleanconf.sh in " $dir
    config/cleanconf.sh
    cd $startdir
  done
fi

