#!/usr/bin/python

def inputdict():

    # This is the full dictionary of input parameters.
    # This must match the input structure in TGLF.

    a={'GEOMETRY_FLAG': '1',
       'FIND_WIDTH': '.true.',
       'NWIDTH': '21',
       'WIDTH' : '1.65',
       'WIDTH_MIN': '0.3',
       'KY': '0.3',
       'NKY': '12',
       'NMODES': '2',
       'IFLUX': '.true.',
       'USE_BPER': '.false.',
       'USE_BPAR': '.false.',
       'USE_BISECTION': '.true.',
       'IBRANCH': '-1',
       'NBASIS_MAX': '4',
       'NBASIS_MIN': '1',
       'NXGRID': '16',
       'ADIABATIC_ELEC': '.false.',
       'ALPHA_P': '1.0',
       'ALPHA_QUENCH': '0.0',
       'ALPHA_E': '0.18',
       'ALPHA_KX0': '1.0',
       'THETA_TRAPPED': '0.7',
       'XNU_FACTOR': '1.0',
       'DEBYE_FACTOR': '1.0',
       'ETG_FACTOR': '1.25',
       'KYGRID_MODEL': '1',
       'XNU_MODEL': '2',
       'SAT_RULE': '1',
       'NS': '2',
       'ZS_1': '-1.0',
       'ZS_2': '1.0',
       'ZS_3': '6.0',
       'MASS_1': '2.723E-4',
       'MASS_2': '1.0',
       'MASS_3': '6.0',
       'RLNS_1': '1.0',
       'RLNS_2': '1.0',
       'RLNS_3': '1.0',
       'RLTS_1': '3.0',
       'RLTS_2': '3.0',
       'RLTS_3': '3.0',
       'VEXB_SHEAR': '0.0',
       'VPAR_SHEAR': '0.0',
       'TAUS_1': '1.0',
       'TAUS_2': '1.0',
       'TAUS_3': '1.0',
       'AS_1': '1.0',
       'AS_2': '1.0',
       'AS_3': '0.0',
       'BETAE': '0.0',
       'XNUEI': '0.0',
       'DEBYE': '0.0',
       'VEXB_MACH': '0.0',
       'VPAR_MACH': '0.0',
       'RMIN_SA': '0.5',
       'RMAJ_SA': '3.0',
       'Q_SA': '2.0',
       'SHAT_SA': '1.0',
       'ALPHA_SA': '0.0',
       'XWELL_SA': '0.0',
       'THETA0_SA': '0.0',
       'B_MODEL_SA': '1',
       'FT_MODEL_SA': '1',
       'RMIN_LOC': '0.5',
       'RMAJ_LOC': '3.0',
       'Q_LOC': '2.0',
       'SHIFT_LOC': '0.0',
       'KAPPA_LOC': '1.0',
       'S_KAPPA_LOC': '0.0',
       'DELTA_LOC': '0.0',
       'S_DELTA_LOC': '0.0',
       'P_PRIME_LOC': '0.0',
       'Q_PRIME_LOC': '16.0',
       'PARK': '1.0',
       'GHAT': '1.0',
       'GCHAT': '1.0',
       'WD_ZERO': '0.1',
       'LINSKER_FACTOR': '0.0',
       'GRADB_FACTOR': '0.0',
       'FILTER': '2.0',
       'X_PSI': '0.0',
       }

    return a

def inputdict_order():

    # Order for dictionary entries

    a=['GEOMETRY_FLAG',
       'FIND_WIDTH',
       'NWIDTH',
       'WIDTH',
       'WIDTH_MIN',
       'KY',
       'NKY',
       'NMODES',
       'IFLUX',
       'USE_BPER',
       'USE_BPAR',
       'USE_BISECTION',
       'IBRANCH',
       'NBASIS_MAX',
       'NBASIS_MIN',
       'NXGRID',
       'ADIABATIC_ELEC',
       'ALPHA_P',
       'ALPHA_QUENCH',
       'ALPHA_E',
       'ALPHA_KX0',
       'THETA_TRAPPED',
       'XNU_FACTOR',
       'DEBYE_FACTOR',
       'ETG_FACTOR',
       'KYGRID_MODEL',
       'XNU_MODEL',
       'SAT_RULE',
       'NS',
       'ZS_1',
       'ZS_2',
       'ZS_3',
       'MASS_1',
       'MASS_2',
       'MASS_3',
       'RLNS_1',
       'RLNS_2',
       'RLNS_3',
       'RLTS_1',
       'RLTS_2',
       'RLTS_3',
       'VEXB_SHEAR',
       'VPAR_SHEAR',
       'TAUS_1',
       'TAUS_2',
       'TAUS_3',
       'AS_1',
       'AS_2',
       'AS_3',
       'BETAE',
       'XNUEI',
       'DEBYE',
       'VEXB_MACH',
       'VPAR_MACH',
       'RMIN_SA',
       'RMAJ_SA',
       'Q_SA',
       'SHAT_SA',
       'ALPHA_SA',
       'XWELL_SA',
       'THETA0_SA',
       'B_MODEL_SA',
       'FT_MODEL_SA',
       'RMIN_LOC',
       'RMAJ_LOC',
       'Q_LOC',
       'SHIFT_LOC',
       'KAPPA_LOC',
       'S_KAPPA_LOC',
       'DELTA_LOC',
       'S_DELTA_LOC',
       'P_PRIME_LOC',
       'Q_PRIME_LOC',
       'PARK',
       'GHAT',
       'GCHAT',
       'WD_ZERO',
       'LINSKER_FACTOR',
       'GRADB_FACTOR',
       'FILTER',
       'X_PSI',
        ]

    return a

def oldinputdict():

    # These are the deprecated parameters.
    # List the parameter, followed by help text.

    a={'OLD_PARAMETER_1': 'new parameter is Y1',
       'OLD_PARAMETER_2': 'new parameter is Y2'
       }

    return a
