#---------------------------
# Toplevel makefile for gapy
#---------------------------

all:
	cd test_geo  ; make
#	cd test_vpro  ; make

clean:
	cd test_geo ; make clean
#	cd test_vpro ; make clean

.IGNORE:
