#---------------------------------------------------------------
# Toplevel makefile for ptglf
#---------------------------------------------------------------

include ${GACODE_ROOT}/platform/build/make.inc.${GACODE_PLATFORM}

all:
	cd src ; make

clean:
	cd src ; make clean

.IGNORE:
